### ISSUE TITLE
.litani_cache_dir discovery can cause run-cbmc-proofs.py failure.

### ISSUE THREAD

**Issue by oliverlavery** [awslabs/aws-build-accumulator#66]
Using Litani to build CBMC proofs we noticed an undesirable behaviour: because litani searches for .litani_cache_dir dotfiles in subdirectories of the cwd as well as parents, a cache dotfile left from a build in a subdirectory can cause a build in a parent directory to fail.

e.g.:

```
lavero in projdir/cbmc/proofs/load_locker_state at docker-hal on  remotes/foo/bar/main/dev [!+?]
➜ cat .litani_cache_dir
/tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d

lavero in projdir/cbmc/proofs/load_locker_state at docker-hal on  remotes/foo/bar/main/dev [!+?]
➜ cd ..

lavero in projdir/cbmc/proofs at docker-hal on  remotes/foo/bar/main/dev [!+?] via 🐍 system
➜ ls
load_locker_state  Makefile-project-defines  Makefile-project-testing   output     run-cbmc-proofs.py
Makefile.common    Makefile-project-targets  Makefile-template-defines  README.md

lavero in projdir/cbmc/proofs at docker-hal on  remotes/foo/bar/main/dev [!+?] via 🐍 system
➜ ./run-cbmc-proofs.py

For your convenience, the output of this run will be symbolically linked to /home/lavero/code/projdir/cbmc/proofs/output/latest/html/index.html

Configuring CBMC proofs: 0 / 1get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
We're adding a job!: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d/jobs
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
We're adding a job!: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d/jobs
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
We're adding a job!: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d/jobs
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
We're adding a job!: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d/jobs
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
We're adding a job!: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d/jobs
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
We're adding a job!: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d/jobs
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
We're adding a job!: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d/jobs
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
We're adding a job!: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d/jobs
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
We're adding a job!: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d/jobs
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
We're adding a job!: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d/jobs
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
We're adding a job!: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d/jobs
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
We're adding a job!: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d/jobs
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
We're adding a job!: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d/jobs
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
We're adding a job!: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d/jobs
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
We're adding a job!: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d/jobs
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
We're adding a job!: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d/jobs
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
We're adding a job!: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d/jobs
get_cache_dir called
_get_cache_dir returning: /tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
Configuring CBMC proofs: 1 / 1
get_cache_dir called
_get_cache_dir returning: /home/lavero/code/projdir/cbmc/proofs/output/litani/runs/6ab1adcf-17dd-4d5c-969f-e482acda3508
get_cache_dir called
_get_cache_dir returning: /home/lavero/code/projdir/cbmc/proofs/output/litani/runs/6ab1adcf-17dd-4d5c-969f-e482acda3508
get_cache_dir called
_get_cache_dir returning: /home/lavero/code/projdir/cbmc/proofs/output/litani/runs/6ab1adcf-17dd-4d5c-969f-e482acda3508
Traceback (most recent call last):
  File "/home/lavero/code/projdir/cbmc/litani/litani", line 844, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/lavero/code/projdir/cbmc/litani/litani", line 840, in main
    await args.func(args)
  File "/home/lavero/code/projdir/cbmc/litani/litani", line 664, in run_build
    litani.add_jobs_to_cache()
  File "/home/lavero/code/projdir/cbmc/litani/lib/litani.py", line 250, in add_jobs_to_cache
    for job_file in os.listdir(jobs_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lavero/code/projdir/cbmc/proofs/output/litani/runs/6ab1adcf-17dd-4d5c-969f-e482acda3508/jobs'
CRITICAL:root:Failed to run litani run-build

lavero in projdir/cbmc/proofs at docker-hal on  remotes/foo/bar/main/dev [!+?] via 🐍 system took 3s
➜
```

This seems like undesirable behaviour, state from builds in a subdirectory shouldn't impact builds in a parent directory.

**Comment by angelonakos** [comment]
Hi Oliver,

Thank you for filling this issue. You mentioned:

> This seems like undesirable behaviour, state from builds in a subdirectory shouldn't impact builds in a parent directory.

In order to determine the cache directory (i.e., directory that contains the `.litani_cache_dir` file), Litani starts by searching the _cwd_. If it fails to find the appropriate file, it will attempt to search for the file inside the parent directories and subdirectories. [Reference: Source Code](https://github.com/awslabs/aws-build-accumulator/blob/release/lib/litani.py#L151-L160)

Based on your logs, my understanding is that:
- The `init` subcommand was executed inside `projdir/cbmc/proofs/load_locker_state`. No _output directory_ was provided during initialization. Additionally, either `/tmp` was specified as the _output prefix_ or the flag was skipped altogether. Hence, the value of `/tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d` when you ran this command:
```
lavero in projdir/cbmc/proofs/load_locker_state at docker-hal on  remotes/foo/bar/main/dev [!+?]
➜ cat .litani_cache_dir
/tmp/litani/runs/ba9fae78-441b-4d2a-b11e-ae18fbe4138d
```
- The `projdir/cbmc/proofs` directory contains the `load_locker_state` , which most likely contains your CBMC proof, the Makefile files originating from the [starter kit](github.com/awslabs/aws-templates-for-cbmc-proofs) as well as an `output` directory. Did you initialize Litani at any point and specify `projdir/cbmc/proofs/output` as your _output directory_ ?
- Based on the rest of the logs, it seems that upon running `run-cbmc-proofs.py` your Litani cache directory was inferred incorrectly, thus, resulting into a `FileNotFoundError` exception being thrown.

We will take a deeper look and determine whether there is a better approach in determining the right cache directory. We will get back to you.

**Comment by karkhaz** [comment]
Thanks for reporting this! I think let's just get rid of this. I wrote it 'just in case', but it has pretty dubious value, and I've seen other people having this same trouble. Thanks for reporting, I'll let you know when we have a release that fixes this!
